## Model tests

In [1]:
import sys
import torch
import torch.nn as nn

sys.path.append("../source/")
from model import Model

In [2]:
sizes = [2, 1, 2, 3]
activations = 3 * [nn.ReLU()] + [None]

In [3]:
mlp = Model(sizes, activations)
print("Number of parameters:", mlp.num_parameters())

Number of parameters: 16


In [4]:
sampled_params = mlp.get_parameters()
print("Initial parameters:", sampled_params)

Initial parameters: tensor([ 0.1845,  0.3335,  0.1002,  0.1059,  0.3386,  0.5242,  0.4933, -0.3118,
        -0.4091,  0.0158,  0.3523, -0.5892, -0.2485,  0.5434, -0.3620,  0.4495],
       grad_fn=<CatBackward0>)


In [5]:
updated_params = sampled_params + torch.rand(len(sampled_params))
print("New parameters:", updated_params)

New parameters: tensor([ 0.3800,  0.5638,  0.8682,  0.7777,  0.5050,  1.1013,  0.5975,  0.2678,
         0.1235,  0.1195,  1.2684, -0.2955,  0.7476,  0.8714, -0.2813,  0.8514],
       grad_fn=<AddBackward0>)


In [6]:
mlp.set_parameters(updated_params)
updated_sampled_params = mlp.get_parameters()
print("Updated parameters:", updated_sampled_params)

Updated parameters: tensor([ 0.3800,  0.5638,  0.8682,  0.7777,  0.5050,  1.1013,  0.5975,  0.2678,
         0.1235,  0.1195,  1.2684, -0.2955,  0.7476,  0.8714, -0.2813,  0.8514],
       grad_fn=<CatBackward0>)


In [7]:
#grad = mlp.get_grad()
#print("Initial grad:", grad)

#updated_grad = grad + torch.rand(len(sampled_params))
#print("New grad:", updated_grad)

#mlp.set_grad(updated_grad)
#updated_grad = mlp.get_grad()
#print("Updated grad:", updated_grad)

In [8]:
mlp

Model(
  (layers): ModuleList(
    (0): Linear(in_features=2, out_features=1, bias=True)
    (1): Linear(in_features=1, out_features=2, bias=True)
    (2): Linear(in_features=2, out_features=3, bias=True)
  )
  (loss): CrossEntropyLoss()
)

In [9]:
batch_size = 10
x = torch.rand(batch_size, sizes[0])
y = torch.randint(low=0, high=sizes[-1], size=(batch_size, ))
x, y

(tensor([[0.1790, 0.7222],
         [0.5919, 0.5301],
         [0.7073, 0.8213],
         [0.9221, 0.3109],
         [0.6596, 0.8614],
         [0.4591, 0.4444],
         [0.7694, 0.5462],
         [0.5989, 0.2000],
         [0.6868, 0.5482],
         [0.2828, 0.1170]]),
 tensor([1, 2, 2, 0, 0, 0, 0, 2, 0, 0]))

In [10]:
mlp.loss(mlp(x), y)

tensor(11.0907, grad_fn=<NllLossBackward0>)

In [11]:
log_target = mlp.compute_log_target(x, y)

In [12]:
mlp.compute_grad_log_target(log_target)

tensor([-1.3964, -1.1848, -2.2313, -0.6806, -4.4561, -1.0043, -3.4460,  4.5694,
         2.7551, -6.2463, -4.9182,  1.5851,  0.0235,  1.3601, -2.5140, -0.2876],
       grad_fn=<CatBackward0>)